"""抖音扫码持久登录（Playwright 持久化 profile，告别手动 cookie）。

为什么需要它
------------
抖音对「手动复制的 Cookie 字符串」极其不友好：时效短、字段多、复制错位置（Set-Cookie
单条 vs 请求头 Cookie 整段）就失效，用户每次都要重来。本模块用 Playwright 的
**持久化浏览器上下文**（user_data_dir）替用户维持一个真实登录会话：

- 首次：``ensure_session()`` 弹出一个真实 Chromium 窗口打开 douyin.com，用户手机
  扫码登录；检测到登录态 cookie 后窗口自动关闭，会话写入 profile。
- 之后：cookie 持久化在 ``backend/data/douyin_profile``，每次下载/转写前用 headless
  持久化 context 自动读取最新 cookie，写成 Netscape 文件给 yt-dlp，**无需再手动复制**。
- 过期：检测到缺少登录态 cookie → 标记 expired，前端把「抖音登录」按钮变「重新登录」，
  用户点一下再次扫码即可（抖音必须扫码，无法静默续期——这是平台限制，不是我们能绕的）。

注意：``ensure_session`` 必须跑在**用户本机**（有显示器、能弹窗）；服务端无头环境
只能做 cookie 读取，弹窗扫码这一步需要在本地执行。沙箱/服务器环境调用 ensure_session
会直接报错，属预期。
"""
from __future__ import annotations

import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Any

from ..system.config import DATA_DIR

log = logging.getLogger("workbench.douyin_session")

PROFILE_DIR = DATA_DIR / "douyin_profile"

# 登录态 cookie 的标志字段：只认「登录后才会下发」的字段。
# 注意：passport_csrf_token / sid_tt 匿名访客也会拿到（CSRF 令牌 / 会话追踪），
# 不能单独作为登录依据——否则浏览器一打开、拿到匿名 cookie 就误报「登录成功」。
_LOGIN_MARKERS = ("sessionid", "uid_tt", "odin_tt")
# 只把 douyin 系域名下的 cookie 写进 Netscape 文件，避免把别的站 cookie 漏给 yt-dlp。
_DOUDOUYIN_HOSTS = ("douyin.com", "iesdouyin.com", "tiktok.com", "bytedance.com")

# 读取 cookie 的缓存（避免每次 yt-dlp 都启动一次 chromium）
_cache: dict[str, Any] = {"path": None, "ts": 0.0, "ttl": 120}

# 启动 chromium 的通用参数：容器/服务器上也能尽量跑起来（仅 headless 读取用）。
_LAUNCH_ARGS = ["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]


def _import_playwright():
    """懒加载 Playwright；没装就返回 None（上层静默回落到手动 cookie）。"""
    try:
        from playwright.sync_api import sync_playwright  # noqa: F401
        return sync_playwright
    except Exception as e:  # noqa: BLE001
        log.debug("[douyin_session] playwright 不可用：%s", e)
        return None


def _has_login_marker(cookies: list[dict]) -> bool:
    names = {c.get("name") for c in cookies}
    return any(m in names for m in _LOGIN_MARKERS)


def _profile_has_cookies_db() -> bool:
    """Chromium 把 cookie 存在 <profile>/Default/Cookies（SQLite）。
    文件不存在 = 从没扫过码 = 肯定没有登录态，直接短路，避免无谓启动 chromium。"""
    return (PROFILE_DIR / "Default" / "Cookies").exists()


def _read_profile_cookies() -> list[dict] | None:
    """用 headless 持久化 context 读取 profile 里的 cookie（不弹窗）。"""
    sync_playwright = _import_playwright()
    if sync_playwright is None:
        return None
    try:
        with sync_playwright() as p:
            ctx = p.chromium.launch_persistent_context(
                str(PROFILE_DIR), headless=True, args=_LAUNCH_ARGS
            )
            try:
                cookies = ctx.cookies()
            finally:
                ctx.close()
        return cookies
    except Exception as e:  # noqa: BLE001
        log.warning("[douyin_session] 读取 profile cookie 失败：%s", e)
        return None


def _write_netscape(cookies: list[dict]) -> str:
    """把 Playwright 的 cookie 列表写成 Netscape cookies.txt，返回路径。"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by douyin_session (Playwright persistent profile)",
    ]
    for c in cookies:
        domain = (c.get("domain") or ".douyin.com").strip()
        # 规范化：去掉前导点重复，统一成 Netscape 需要的 .domain 形式
        if domain and not domain.startswith("."):
            domain = "." + domain.lstrip(".")
        host = domain.lstrip(".")
        if not any(h in host for h in _DOUDOUYIN_HOSTS):
            continue
        name = c.get("name", "")
        value = c.get("value", "")
        path_ = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = c.get("expires")
        if exp is None or exp <= 0:
            exp = 2147483647  # 永不过期（让 yt-dlp 不因为过期拒绝）
        else:
            exp = int(exp)
        lines.append(f"{domain}\tTRUE\t{path_}\t{secure}\t{exp}\t{name}\t{value}")
    body = "\n".join(lines) + "\n"
    fd, p = tempfile.mkstemp(prefix="dy_session_", suffix=".txt")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(body)
    return p


def _markers_from_netscape(path: str) -> list[str]:
    """从缓存的 Netscape cookie 文件里提取命中的登录标记（供 session_status 兜底用）。"""
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.readlines()
    except Exception:
        return []
    names: set[str] = set()
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        names.add(parts[5])
    return [m for m in _LOGIN_MARKERS if m in names]


def _count_from_netscape(path: str) -> int:
    """统计 Netscape cookie 文件里有效 cookie 条数。"""
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.readlines()
    except Exception:
        return 0
    return sum(1 for line in lines if line.strip() and not line.startswith("#"))


def get_cookie_netscape_file(force: bool = False) -> str | None:
    """返回可用于 yt-dlp cookiefile 的 Netscape 文件路径；无有效会话返回 None。

    优先用内存缓存（TTL 120s），避免每次下载都启动一次 chromium。
    """
    now = time.time()
    if not force and _cache.get("path") and now - _cache["ts"] < _cache["ttl"]:
        if os.path.isfile(_cache["path"]):
            return _cache["path"]
    # 还没扫过码 → 直接短路
    if not _profile_has_cookies_db():
        return None
    cookies = _read_profile_cookies()
    if not cookies or not _has_login_marker(cookies):
        return None
    path = _write_netscape(cookies)
    _cache["path"] = path
    _cache["ts"] = now
    return path


def session_status() -> dict:
    """给前端展示当前扫码登录状态。"""
    # 优先看内存缓存：Chromium 落盘 SQLite 有延迟，先靠缓存避免误报「未登录」。
    # 也顺带兜住「ensure_session 刚拿到 cookie 但磁盘还没写」的窗口期。
    cached = _cache.get("path")
    if cached and os.path.isfile(cached) and (time.time() - _cache["ts"]) < _cache["ttl"]:
        markers = _markers_from_netscape(cached)
        if markers:
            return {
                "exists": True,
                "logged_in": True,
                "cookie_count": _count_from_netscape(cached),
                "markers": markers,
                "note": "会话有效（来自内存缓存）。",
            }
    if not _profile_has_cookies_db():
        return {
            "exists": False,
            "logged_in": False,
            "cookie_count": 0,
            "markers": [],
            "note": "尚未扫码登录；点「抖音登录」用手机扫码一次即可。",
        }
    cookies = _read_profile_cookies()
    if cookies is None:
        return {
            "exists": True,
            "logged_in": False,
            "cookie_count": 0,
            "markers": [],
            "note": "无法读取 profile（playwright 未安装或被占用）。",
        }
    markers = [m for m in _LOGIN_MARKERS if any(c.get("name") == m for c in cookies)]
    return {
        "exists": True,
        "logged_in": bool(markers),
        "cookie_count": len(cookies),
        "markers": markers,
    }


def ensure_session(timeout: int = 300) -> dict:
    """确保有一个有效的登录会话。

    - 已有有效会话 → 直接返回 ``{"ok": True, "already": True}``，不弹窗。
    - 没有 → 弹出一个**有头** Chromium 窗口打开 douyin.com，轮询 cookie 直到出现
      登录态标记（用户在手机上扫码）；超时（默认 300s）则返回失败。

    必须在用户本机执行（需要显示器弹窗）。无头/沙箱环境会直接报错，属预期。
    """
    # 已有有效会话就别弹窗了
    if get_cookie_netscape_file() is not None:
        return {"ok": True, "already": True}

    sync_playwright = _import_playwright()
    if sync_playwright is None:
        return {
            "ok": False,
            "error": "playwright 未安装。请在后端环境执行：pip install playwright && playwright install chromium",
        }

    try:
        with sync_playwright() as p:
            # 有头模式：必须让用户能看到窗口并扫码
            ctx = p.chromium.launch_persistent_context(
                str(PROFILE_DIR), headless=False, args=_LAUNCH_ARGS
            )
            try:
                page = ctx.new_page()
                page.goto("https://www.douyin.com/", timeout=30000)
                # 打开瞬间若已是登录态（profile 里已有真会话，无需扫码）→ 直接复用，
                # 否则匿名访客的 passport_csrf_token / sid_tt 会被误判成「登录成功」。
                cookies0 = ctx.cookies()
                if _has_login_marker(cookies0):
                    path = _write_netscape(cookies0)
                    _cache["path"] = path
                    _cache["ts"] = time.time()
                    return {"ok": True, "already": True}
                # 不是登录态 → 轮询等待用户手机扫码
                deadline = time.time() + timeout
                logged_in = False
                while time.time() < deadline:
                    cookies = ctx.cookies()
                    if _has_login_marker(cookies):
                        logged_in = True
                        # 立即把内存里的 cookie 落盘成 Netscape 并暖缓存，
                        # 不依赖 Chromium 异步落盘 SQLite 的时机（否则徽标会短暂误报未登录）
                        path = _write_netscape(cookies)
                        _cache["path"] = path
                        _cache["ts"] = time.time()
                        break
                    time.sleep(2)
            finally:
                ctx.close()
    except Exception as e:  # noqa: BLE001
        return {"ok": False, "error": f"启动登录窗口失败：{str(e)[:200]}（需在用户本机运行）"}

    if not logged_in:
        return {"ok": False, "error": f"等待扫码登录超时（{timeout}s），请重试。"}

    return {"ok": True, "already": False}
